const prodcuts = [
  {
    name: "Product 1",
    description: "Description for Product 1",
    imageSrc: "image1.jpg",
    price: 19.99,
    stockQty: 50,
    minStockQty: 10,
  },
  {
    name: "Product 2",
    description: "Description for Product 2",
    imageSrc: "image2.jpg",
    price: 29.99,
    stockQty: 100,
    minStockQty: 20,
  },
  {
    name: "Product 3",
    description: "Description for Product 3",
    imageSrc: "image3.jpg",
    price: 9.99,
    stockQty: 30,
    minStockQty: 5,
  },
  {
    name: "Product 4",
    description: "Description for Product 4",
    imageSrc: "image4.jpg",
    price: 49.99,
    stockQty: 75,
    minStockQty: 15,
  },
  {
    name: "Product 5",
    description: "Description for Product 5",
    imageSrc: "image5.jpg",
    price: 99.99,
    stockQty: 40,
    minStockQty: 10,
  },
];
